run:
  tests: true
  timeout: 5m
  concurrency: 4

linters:
  enable:
    - asciicheck
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - gci
    - goconst
    - gocritic
    - godot
    # Enable this later when design etc are more finalized
    # - godox
    - gofumpt
    - gomodguard
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(cosmossdk.io)
      - prefix(github.com/cosmos/cosmos-sdk)
      - prefix(github.com/cometbft/cometbft)
      - prefix(github.com/exocore)
      - prefix(github.com/ExocoreNetwork/exocore)
    custom-order: true
  gofumpt:
    lang-version: "1.20"
  gomodguard:
    blocked:
      versions:                                                         # List of blocked module version constraints
        - https://github.com/etcd-io/etcd:                              # Blocked module with version constraint
            version: ">= 3.4.10 || ~3.3.23"                             # Version constraint, see https://github.com/Masterminds/semver#basic-comparisons
            reason: "CVE-2020-15114; CVE-2020-15136; CVE-2020-15115"    # Reason why the version constraint exists. (Optional)
        - https://github.com/dgrijalva/jwt-go:                          # Blocked module with version constraint
            version: ">= 4.0.0-preview1"                                # Version constraint, see https://github.com/Masterminds/semver#basic-comparisons
            reason: "CVE-2020-26160"                                    # Reason why the version constraint exists. (Optional)
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
  revive:
    ignore-generated-header: true
    severity: error
    enable-all-rules: true
    rules:
    - name: line-length-limit
      arguments: [96]
    - name: add-constant
      arguments:
      - "allowInts": "0,1,8"
  staticcheck:
    checks: [ "all" ]
  varnamelen:
    # allow names like transaction tx, priv key pk, bank keeper bk
    min-name-length: 2
    check-receiver: false
    check-return: false
    check-type-param: false
    ignore-type-assert-ok: false
    ignore-map-index-ok: false
    ignore-chan-recv-ok: false
    ignore-names:
      - err
    ignore-decls:
      - t testing.T
      - e error
      - i int
      - j int
      - k int
      - T any
      - m map[string]int
      - c sdk.Context