version: "3"

services:
  exocorenode0:
    container_name: exocorenode0
    image: "exocore/node"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-exocore.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "8545:8545"
      - "26661:26660"
    volumes:
      - ./build/.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  exocorenode1:
    container_name: exocorenode1
    image: "exocore/node"
    environment:
      - DEBUG=0
      - ID=1
      - LOG=${LOG:-exocore.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "8546:8545"
      - "26662:26660"
    volumes:
      - ./build/.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  exocorenode2:
    container_name: exocorenode2
    image: "exocore/node"
    environment:
      - DEBUG=0
      - ID=2
      - LOG=${LOG:-exocore.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "8547:8545"
      - "26663:26660"
    volumes:
      - ./build/.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  exocorenode3:
    container_name: exocorenode3
    image: "exocore/node"
    environment:
      - DEBUG=0
      - ID=3
      - LOG=${LOG:-exocore.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "8548:8545"
      - "26664:26660"
    volumes:
      - ./build/.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/18
