name: AnteHandler Benchmark Tests

permissions:
  contents: read

on:
  push:
    branches:
      - develop
      - main
      - master
    paths:
      - 'app/ante/**'
  pull_request:
    branches:
      - develop
      - main
      - master
    paths:
      - 'app/ante/**'

jobs:
  ante-benchmark-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.12'
          check-latest: true

      - name: Run benchmark tests
        run: go test -bench=. ./app/ante/... -benchtime=1000x

