name: "Consensus Warn"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    permissions:
      contents: read
      pull-requests: write  # For reading the PR and posting comment
    runs-on: ubuntu-latest
    steps:
      # This is used for warning when a PR touches any of the roots, or any function or method directly or indirectly called by a root
      - uses: actions/checkout@v4
      - uses: orijtech/consensuswarn@956f047a43f56021a28afdfb2a2291a20955f48d
        with:
          # example.com/pkg/path.Type.Method
          roots: 'github.com/ExocoreNetwork/exocore/app.ExocoreApp.DeliverTx,github.com/ExocoreNetwork/exocore/app.ExocoreApp.BeginBlocker,github.com/ExocoreNetwork/exocore/app.ExocoreApp.EndBlocker'
