name: "Consensus Warn"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    permissions:
      pull-requests: write  # For reading the PR and posting comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: orijtech/consensuswarn@main
        with:
          roots: 'github.com/ExocoreNetwork/exocore/app.ExocoreApp.BaseApp.DeliverTx,github.com/ExocoreNetwork/exocore/app.ExocoreApp.BaseApp.BeginBlocker,github.com/ExocoreNetwork/exocore/app.ExocoreApp.BaseApp.EndBlocker'
