name: E2E Test

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
      - main
      - master
  push:
    branches:
      - develop
      - main
      - master

jobs:
  test-e2e:
    # disabled for now, since we don't have any e2e tests.
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            app/app.go
            app/upgrades/*
            go.mod
            go.sum
            tests/e2e/*
      - name: Test E2E
        run: |
          make test-e2e
        if: env.GIT_DIFF

