name: Lint
# Lint runs golangci-lint over the entire exocore repository. The `golangci` will pass without
# running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - master

permissions:
  contents: read

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Required: setup-go, for all versions v3.0.0+ of golangci-lint
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.12'
          # Use pinned versions, not git versions
          check-latest: false
          # Match `golangci-lint-action` recommendation
          cache: false
      - uses: actions/checkout@v4
      # Only operate if there are any differences in go files
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      # Now, the actual golangci-lint configuration
      - uses: golangci/golangci-lint-action@v4
        with:
          # Required parameter
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        # Check only if there are differences in the source code
        if: "env.GIT_DIFF"
  markdown-lint:
    name: Run markdown-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.md
      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yml
          ignore_path: .markdownlintignore
        # Check only if there are differences in the source code
        if: env.GIT_DIFF
