name: Check Markdown links

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - develop
      - main
      - master
    paths:
      - '**.md'
  # runs every monday at 9 am
  schedule:
    - cron: "0 9 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@master
        with:
          base-branch: "main"
          config-file: "mlc_config.json"
