name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a .proto file has been changed
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "proto/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.proto
            **/buf.yaml
            buf.work.yaml
            buf.gen.yaml
      - run: |
          make proto-gen
        if: env.GIT_DIFF

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.26.1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"

  break-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.26.1
      - uses: bufbuild/buf-breaking-action@v1
        id: break-check
        with:
          input: "proto"
          # previously, this ran on ref=HEAD~1, which is incorrect as it can
          # only be used to compare within a branch. it is designed to run
          # on a PR, so it must compare the HEAD of the base branch against
          # the PR branch.
          against: "https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},subdir=proto"
        # do not fail the build if there are breaking changes
        continue-on-error: true
      - name: Find previous comment, if any
        id: find-comment
        uses: peter-evans/find-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: buf
        if: steps.break-check.outcome == 'failure'
      - name: Comment status of break-check
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            ${{ github.sha }} (${{ github.event.pull_request.updated_at }}) has a buf breaking change.
            View the workflow run: [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          edit-mode: append
        if: steps.break-check.outcome == 'failure'
