name: Solhint
# This workflow is only run when a file in the contracts folder changes.
on:
  pull_request:
    paths:
      - "contracts/**"

permissions:
  contents: read

jobs:
  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm install -g solhint
      - run: solhint --version
      - run: solhint 'contracts/**/*.sol'
