name: Tests
on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - master
      - release/**

permissions:
  contents: write
  pull-requests: write

# Automatically cancel run if another commit to the same ref is detected.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unit-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test and Create Coverage Report
        run: |
          make test-unit-cover
        if: env.GIT_DIFF
      - name: check test coverage
        if: github.event_name == 'pull_request'
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/ExocoreNetwork/exocore
          threshold-total: 70
          badge-file-name: coverage.svg
      - name: Comment coverage on PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const path = './coverage.svg';
            const svgContent = fs.readFileSync(path, {encoding: 'utf8'});
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Test Coverage Badge\n\n![Coverage Badge](${svgContent})`
            });
